# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_billing}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-14}
  s.description = %q{This is a plugin for Redmine}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/accounts_payables_controller.rb",
     "app/helpers/vendor_invoices_helper.rb",
     "app/models/billing_export.rb",
     "app/models/billing_status.rb",
     "app/models/billing_type.rb",
     "app/models/fixed_vendor_invoice.rb",
     "app/models/hourly_vendor_invoice.rb",
     "app/models/selected_time_entry.rb",
     "app/models/vendor_invoice.rb",
     "app/models/vendor_invoice_filter.rb",
     "app/views/accounts_payables/_autocomplete.html.erb",
     "app/views/accounts_payables/_filters.html.erb",
     "app/views/accounts_payables/_hours_without_rates.html.erb",
     "app/views/accounts_payables/bulk_edit.html.erb",
     "app/views/accounts_payables/context_menu.html.erb",
     "app/views/accounts_payables/edit.html.erb",
     "app/views/accounts_payables/index.html.erb",
     "app/views/accounts_payables/show.html.erb",
     "app/views/accounts_payables/timesheet.html.erb",
     "assets/images/clock.png",
     "assets/images/invoice.png",
     "assets/images/page_excel.png",
     "assets/images/table_add.png",
     "assets/images/table_edit.png",
     "assets/images/table_multiple.png",
     "assets/javascripts/billing-timesheet.js",
     "assets/javascripts/facebox.js",
     "assets/javascripts/jquery-1.2.6.min.js",
     "assets/javascripts/jquery.dimensions.min.js",
     "assets/javascripts/jquery.js-link.js",
     "assets/stylesheets/b.png",
     "assets/stylesheets/billing-timesheet.css",
     "assets/stylesheets/billing.css",
     "assets/stylesheets/bl.png",
     "assets/stylesheets/br.png",
     "assets/stylesheets/closelabel.gif",
     "assets/stylesheets/facebox.css",
     "assets/stylesheets/loading.gif",
     "assets/stylesheets/tl.png",
     "assets/stylesheets/tr.png",
     "config/locales/en.yml",
     "init.rb",
     "lang/en.yml",
     "lib/billing_compatibility.rb",
     "lib/billing_project_hooks.rb",
     "lib/billing_routing_hooks.rb",
     "lib/billing_time_entry_patch.rb",
     "lib/billing_timelog_hooks.rb",
     "lib/billing_timesheet_hooks.rb",
     "lib/billing_timesheet_patch.rb",
     "lib/billing_user_patch.rb",
     "lib/tasks/plugin_stat.rake",
     "rails/init.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redmine_billing}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This is a plugin for Redmine}
  s.test_files = [
    "spec/lib/billing_timesheet_hooks_spec.rb",
     "spec/lib/timesheet_status_filters_spec.rb",
     "spec/spec_helper.rb",
     "spec/models/selected_time_entry_spec.rb",
     "spec/models/vendor_invoice_spec.rb",
     "spec/models/hourly_vendor_invoice_spec.rb",
     "spec/models/vendor_invoice_filter_spec.rb",
     "spec/models/fixed_vendor_invoice_spec.rb",
     "spec/models/billing_export_spec.rb",
     "spec/controllers/accounts_payables_controller_spec.rb",
     "spec/sanity_spec.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
